version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  # ng-demo examples
  - package-ecosystem: "npm"
    directory: "/src/code/ng-demo"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "angular*"
        update-types: ["version-update:semver-minor","version-update:semver-patch"]
  - package-ecosystem: "npm"
    directory: "/src/code/ng-demo-auth0"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor","version-update:semver-patch"]
  - package-ecosystem: "npm"
    directory: "/src/code/ng-demo-bootstrap"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor","version-update:semver-patch"]
  - package-ecosystem: "npm"
    directory: "/src/code/ng-demo-material"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor","version-update:semver-patch"]
  # angular + spring-boot examples
  - package-ecosystem: "npm"
    directory: "/src/code/angular-spring-boot/notes"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor","version-update:semver-patch"]
  - package-ecosystem: "gradle"
    directory: "/src/code/angular-spring-boot/notes-api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/src/code/angular-bootstrap/notes"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor","version-update:semver-patch"]
  - package-ecosystem: "gradle"
    directory: "/src/code/angular-bootstrap/notes-api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/src/code/angular-deployment/notes"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor","version-update:semver-patch"]
  - package-ecosystem: "gradle"
    directory: "/src/code/angular-deployment/notes-api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/src/code/angular-docker/notes"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor","version-update:semver-patch"]
  - package-ecosystem: "gradle"
    directory: "/src/code/angular-docker/notes-api"
    schedule:
      interval: "weekly"
