runtime:
  cache_dir: ./.cache/antora
site:
  title: The Angular Mini-Book
content:
  sources:
    - url: '.'
      branches: HEAD
      start_path: src/docs/asciidoc
ui:
  bundle:
    url: https://github.com/Mogztter/mini-book-default-ui/releases/download/v0.3.2/ui-bundle.zip
    snapshot: true
  supplemental_files: ./src/docs/supplemental-ui
output:
  dir: ./public
