= Acknowledgments

I'm incredibly grateful to Trish, Abbie, and Jack. They put up with my late nights and extended screen time while I worked on this book.

To Miško Hevery, thank you for inventing Angular and changing the lives of front-end developers. To the whole Angular team, I appreciate you and all you do for the community. Kudos for making our apps faster with every release!

Thanks to Phil Webb and Dave Syer for creating Spring Boot and simplifying Java for everyone. Hats off to the whole Spring team for their tireless dedication to quality open source projects.

I want to thank this book's tech editor, Deepu K Sasidharan. I looked to him for his deep experience with both TypeScript and JavaScript. Many sections are more streamlined because of his advice.

This book's copy editor, Maureen Spencer, helped correct my grammar and make this book easier on the eyes. I'm thankful for your help, Maureen.

Finally, my compliments to you, dear reader. It's a heckuva time to be writing code. Enjoy your learning adventures!
