name: Angular Demo CI

on: [push, pull_request]

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'app' output variable
      app: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            demo:
              - src/code/ng-demo/**
            demo-bootstrap:
              - src/code/ng-demo-bootstrap/**
            demo-material:
              - src/code/ng-demo-material/**
            demo-auth0:
              - src/code/ng-demo-auth0/**

  build:
    name: Build and test
    needs: changes
    if: ${{ needs.changes.outputs.services != '[]' && needs.changes.outputs.services != '' }}
    strategy:
      fail-fast: false
      matrix:
        app: ng-${{ fromJson(needs.changes.outputs.app) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/code/${{ matrix.app }}
    steps:
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install latest Chrome
        run: |
          sudo apt update
          sudo apt --only-upgrade install google-chrome-stable
          google-chrome --version
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: xvfb-run npm test -- --watch=false
      - name: Sets Cypress credentials for Auth0
        if: ${{ matrix.app == 'ng-demo-auth0' }}
        env:
          CYPRESS_E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
          CYPRESS_E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
      - name: Run integration tests
        uses: cypress-io/github-action@v3
        with:
          build: npm run build
          start: npm start
          working-directory: ./src/code/${{ matrix.app }}
          wait-on: http://localhost:4200
          browser: chrome
