name: Angular Demo CI

on: [push, pull_request]

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure demos to test
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ng-demo: src/code/ng-demo/**
            ng-demo-bootstrap: src/code/ng-demo-bootstrap/**
            ng-demo-material: src/code/ng-demo-material/**
            ng-demo-auth0: src/code/ng-demo-auth0/**

  build:
    name: Build and test
    needs: changes
    if: ${{ needs.changes.outputs.app != '[]' && needs.changes.outputs.app != '' }}
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJson(needs.changes.outputs.app) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/code/${{ matrix.app }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install latest Chrome
        run: |
          sudo apt update
          sudo apt --only-upgrade install google-chrome-stable
          google-chrome --version
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: xvfb-run npm test -- --watch=false
      - name: Run integration tests
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_E2E_DOMAIN: ${{ secrets.E2E_DOMAIN }}
          CYPRESS_E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
          CYPRESS_E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
        with:
          browser: chrome
          start: npm start
          working-directory: src/code/${{ matrix.app }}
          wait-on: http://[::1]:4200
