name: Angular Demo CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        app: [ ng-demo, ng-demo-bootstrap, ng-demo-material, ng-demo-auth0 ]
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/code/${{ matrix.app }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install latest Chrome
        run: |
          sudo apt update
          sudo apt --only-upgrade install google-chrome-stable
          google-chrome --version
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: xvfb-run npm test -- --watch=false
      - name: Run integration tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          working-directory: ./src/code/${{ matrix.app }}
          wait-on: http://localhost:4200
