name: Angular + Spring Boot CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        app: [spring-boot, bootstrap, deployment, docker]
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'
      - name: Install latest Chrome
        run: |
          sudo apt update
          sudo apt --only-upgrade install google-chrome-stable
          google-chrome --version
      - name: Install Angular dependencies
        working-directory: ./src/code/angular-${{ matrix.app }}/notes
        run: npm ci
      - name: Run Angular tests
        working-directory: ./src/code/angular-${{ matrix.app }}/notes
        run: xvfb-run npm test -- --watch=false
      - name: Run Spring Boot tests
        working-directory: ./src/code/angular-${{ matrix.app }}/notes-api
        run: ./gradlew test
