name: Angular + Spring Boot CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        app: [spring-boot, bootstrap, deployment, docker]
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/code/angular-${{ matrix.app }}/notes
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/code/angular-${{ matrix.app }}/**'
      - name: Checkout
        if: steps.changes.outputs.src == 'true'
        uses: actions/checkout@v3
      - name: Use Node 16
        if: steps.changes.outputs.src == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-java@v3
        if: steps.changes.outputs.src == 'true'
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Install latest Chrome
        if: steps.changes.outputs.src == 'true'
        run: |
          sudo apt update
          sudo apt --only-upgrade install google-chrome-stable
          google-chrome --version
      - name: Install Angular dependencies
        if: steps.changes.outputs.src == 'true'
        run: npm ci
      - name: Run Angular tests
        if: steps.changes.outputs.src == 'true'
        run: xvfb-run npm test -- --watch=false
      - name: Run Spring Boot tests
        if: steps.changes.outputs.src == 'true'
        working-directory: ./src/code/angular-${{ matrix.app }}/notes-api
        run: ./gradlew test
