name: Angular + Spring Boot CI

on: [ push, pull_request ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'app' output variable
      app: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            spring-boot:
              - src/code/angular-spring-boot/**
            bootstrap:
              - src/code/angular-bootstrap/**
            deployment:
              - src/code/angular-deployment/**
            docker:
              - src/code/angular-docker/**

  build:
    needs: changes
    if: ${{ needs.changes.outputs.services != '[]' && needs.changes.outputs.services != '' }}
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJson(needs.changes.outputs.app) }}
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/code/angular-${{ matrix.app }}/notes
    steps:
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Install latest Chrome
        run: |
          sudo apt update
          sudo apt --only-upgrade install google-chrome-stable
          google-chrome --version
      - name: Install Angular dependencies
        run: npm ci
      - name: Run Angular tests
        run: xvfb-run npm test -- --watch=false
      - name: Run Spring Boot tests
        working-directory: ./src/code/angular-${{ matrix.app }}/notes-api
        run: ./gradlew test
