name: Angular + Spring Boot CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        app: [spring-boot, bootstrap, deployment, docker]
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/code/angular-${{ matrix.app }}/notes
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14.x'
      - name: Install latest Chrome
        run: |
          sudo apt update
          sudo apt --only-upgrade install google-chrome-stable
          google-chrome --version
      - name: Install Angular dependencies
        run: npm ci
      - name: Run Angular tests
        run: xvfb-run npm test -- --watch=false
      - name: Run Spring Boot tests
        working-directory: ./src/code/angular-${{ matrix.app }}/notes-api
        run: ./gradlew test
