name: Update examples to use Angular 16 and Spring Boot 3.1

on: [pull_request]

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Upgrade to Angular 16
        run: |
          ANGULAR_VERSION="16.0.0-rc.0"
          echo "Upgrading to Angular $ANGULAR_VERSION"
          npm i -g @angular/cli@$ANGULAR_VERSION
          for dir in $(find src/code -name 'package.json' -not -path '*/node_modules/*' -exec dirname {} \;); do
            origin=$(pwd)
            echo "Upgrading $dir"
            cd $dir && npm ci && ng update @angular/core @angular/cli --next --force && cd $origin
          done

      - name: Upgrade to Spring Boot 3.1
        run: |
          SPRING_BOOT_VERSION="3.1.0-M2"
          echo "Upgrading to Spring Boot $SPRING_BOOT_VERSION"
          for dir in $(find src/code -name 'build.gradle.kts' -exec dirname {} \;); do
            origin=$(pwd)
            echo "Upgrading $dir"
            sed -i "s/^.*id(\"org.springframework.boot\") version .*\$/id(\"org.springframework.boot\") version \"$SPRING_BOOT_VERSION\"/" $dir/build.gradle.kts
            sed -i "s|^.*repositories.*\$|repositories { mavenCentral(); maven { url = uri(\"https://repo.spring.io/milestone\") } }|" $dir/build.gradle.kts
            echo 'pluginManagement {\n    repositories {\n        maven { url = uri("https://repo.spring.io/milestone") }\n        gradlePluginPortal()\n    }\n}' >> $dir/settings.gradle.kts
            cd $origin
          done


      - name: Run Angular tests
        run: |
          for dir in $(find src/code -name 'package.json' -not -path '*/node_modules/*' -exec dirname {} \;); do
            origin=$(pwd)
            echo "Running tests in $dir"
            cd $dir && xvfb-run ng test --watch=false && cd $origin
          done

      - name: Run Spring Boot tests
        run: |
          for dir in $(find src/code -name 'build.gradle.kts' -exec dirname {} \;); do
            echo "Running tests in $dir"
            origin=$(pwd)
            cd $dir && ./gradlew test && cd $origin
          done
