name: Update examples to use Angular 16 and Spring Boot 3.1

on: [pull_request]

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Upgrade to Angular 16
        run: |
          ANGULAR_VERSION="16.0.0-rc.0" # this could change as it's not dependent on --next
          echo "Upgrading to Angular $ANGULAR_VERSION"
          find src/code -name 'package.json' -not -path '*/node_modules/*' -execdir npm ci \;
          find src/code -name 'package.json' -not -path '*/node_modules/*' -execdir ng update @angular/core @angular/cli --next \;

      - name: Upgrade to Spring Boot 3.1
        run: |
          SPRING_BOOT_VERSION="3.1.0-M2"
          echo "Upgrading to Spring Boot $SPRING_BOOT_VERSION"
          find src/code -name 'build.gradle.kts' -exec sed -i "s/^.*id(\"org.springframework.boot\") version .*\$/id(\"org.springframework.boot\") version \"$SPRING_BOOT_VERSION\"/" {} \;
          find src/code -name 'build.gradle.kts' -exec sed -i "s|^.*repositories.*\$|repositories { mavenCentral(); maven { url = uri(\"https://repo.spring.io/milestone\") } }|" {} \;

      - name: Run Angular tests
        run: |
          for dir in $(find src/code -name 'package.json' -not -path '*/node_modules/*' -exec dirname {} \;); do
            origin=$(pwd)
            echo "Running tests in $dir"
            cd $dir && xvfb-run ng test --watch=false && cd $origin
          done

      - name: Run Spring Boot tests
        run: |
          for dir in $(find src/code 'build.gradle.kts' -exec dirname {} \;); do
            echo "Running tests in $dir"
            cd $dir && ./gradlew test && cd ~
          done
